#!/usr/bin/env bash

# This gets the directory where the script is stored
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi

  shift
done

log () {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute () {
  log "Execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "------------------ DEV ENV ------------------"

copy_dir () {
  from="$1"
  to="$2"
  
  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file () {
  from="$1"
  to="$2"
  name=$(basename $from)
  
  execute rm $to/$name
  execute cp $from $to/$name
}

add_config () {
  if [[ -f $HOME/.zshrc ]]; then
    execute grep "$@" ~/.zshrc || echo "$@" >> ~/.zshrc
  fi
  if [[ -f $HOME/.bashrc ]]; then
    execute grep "$@" ~/.bashrc || echo "$@" >> ~/.bashrc
  fi
  
}

# Note: WSL 2 Does have XDG_CONFIG HOME so run uncomment this if that's the case
# log $XDG_CONFIG_HOME
# execute mkdir $HOME/.config
# TODO: Fix the issue with the config path
# execute export XDG_CONFIG_HOME="$HOME/.config"

# Copy configurations from dev-env to OS Configs
# copy_dir .config $XDG_CONFIG_HOME
# copy_dir .local $XDG_CONFIG_HOME

# TODO: This is to update neovim config
execute rm -rf $HOME/.cofig/nvim
execute rsync -lrv --exclude .git ~/personal/kickstart.nvim/* $HOME/.config/nvim


# TODO: This is to update tmux config
execute rm -rf $HOME/.cofig/tmux
execute cp -r .config/tmux $HOME/.config/tmux

if [[ -f ~/.bashrc ]]; then
  execute grep "export XDG_CONFIG_HOME=\$HOME/.config" ~/.bashrc || echo "export XDG_CONFIG_HOME=\$HOME/.config" >> ~/.bashrc
  execute grep "export XDG_CACHE_HOME=\$HOME/.cache" ~/.bashrc || echo "export XDG_CACHE_HOME=\$HOME/.cache" >> ~/.bashrc
  execute grep "export XDG_DATA_HOME=\$HOME/.local/share" ~/.bashrc || echo "export XDG_DATA_HOME=\$HOME/.local/share" >> ~/.bashrc
  execute grep "export XDG_STATE_HOME=\$HOME/.local/state" ~/.bashrc || echo "export XDG_STATE_HOME=\$HOME/.local/state" >> ~/.bashrc

  execute grep "alias vi=nvim" ~/.bashrc || echo "alias vi=nvim" >> ~/.bashrc
fi
if [[ -f ~/.zshrc ]]; then
  execute grep "export XDG_CONFIG_HOME=\$HOME/.config" ~/.zshrc || echo "export XDG_CONFIG_HOME=\$HOME/.config" >> ~/.zshrc
  execute grep "export XDG_CACHE_HOME=\$HOME/.cache" ~/.zshrc || echo "export XDG_CACHE_HOME=\$HOME/.cache" >> ~/.zshrc
  execute grep "export XDG_DATA_HOME=\$HOME/.local/share" ~/.zshrc || echo "export XDG_DATA_HOME=\$HOME/.local/share" >> ~/.zshrc
  execute grep "export XDG_STATE_HOME=\$HOME/.local/state" ~/.zshrc || echo "export XDG_STATE_HOME=\$HOME/.local/state" >> ~/.zshrc

  execute grep "alias vi=nvim" ~/.zshrc || echo "alias vi=nvim" >> ~/.zshrc
fi

add_config "export XDG_CONFIG_HOME=\$HOME/.config"
add_config "export XDG_CACHE_HOME=\$HOME/.cache"
add_config "export XDG_DATA_HOME=\$HOME/.local/share"
add_config "export XDG_STATE_HOME=\$HOME/.local/state"

add_config "alias vi=nvim"
add_config "set -o vi"

if [[ -n "$BASH_VERSION" ]]; then
	execute source $HOME/.bashrc
fi
if [[ -n "$ZSH_NAME" ]]; then
	execute source $HOME/.zshrc
fi
