#!/usr/bin/env bash

# This gets the directory where the script is stored
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi

  shift
done

log () {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute () {
  log "Execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

log "------------------ DEV ENV ------------------"

copy_dir () {
  from="$1"
  to="$2"
  
  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file () {
  from="$1"
  to="$2"
  name=$(basename $from)
  
  execute rm $to/$name
  execute cp $from $to/$name
}

# Note: WSL 2 Does have XDG_CONFIG HOME so run uncomment this if that's the case
log $XDG_CONFIG_HOME
# execute mkdir $HOME/.config
# TODO: Fix the issue with the config path
# execute export XDG_CONFIG_HOME="$HOME/.config"

# Copy configurations from dev-env to OS Configs
copy_dir .config $XDG_CONFIG_HOME
copy_dir .local $XDG_CONFIG_HOME

rm -rf $XDG_CONFIG_HOME/nvim
cp -r ~/personal/kickstart.nvim $XDG_CONFIG_HOME/nvim


