#!/usr/bin/env bash

# ZSH
sudo apt install zsh
sudo chsh -s $(which zsh)

# OH MY ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# FZF
git clone https://github.com/junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install

# Rust + Cargo
curl https://sh.rustup.rs -sSf | sh

# Node NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion

nvim install node

# Python
sudo apt install python3-venv

# WSL Utilities for WSL based setup
if [[ -f /etc/wsl.conf ]]; then
    sudo apt install wslu
fi
