#!/usr/bin/env bash

sudo apt-get install ninja-build gettext cmake unzip curl build-essential

git clone -b stable https://github.com/neovim/neovim.git ~/personal/neovim
cd ~/personal/neovim

make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
